name: Automatische Artikelerstellung

on:
  schedule:
    - cron: "0 0 * * *" # Führt den Workflow täglich um 00:00 Uhr UTC aus
  workflow_dispatch: # Ermöglicht auch manuelles Auslösen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v2

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Artikel generieren
        run: node generate.js

      - name: Änderungen committen und pushen
        run: |
          git config --local user.name "Niklas223"
          git config --local user.email "internetspam22@gmx.de"
          git add posts/
          git commit -m "Automatisch generierter Artikel"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
